In [3]:
import pandas as pd
df = pd.read_csv('bank_transtaction_dataset.csv')
df.head(10)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
0,TX000001,AC00128,14.09,4/11/2023 16:29,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21
1,TX000002,AC00455,376.24,6/27/2023 16:44,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91
2,TX000003,AC00019,126.29,7/10/2023 18:16,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35
3,TX000004,AC00070,184.50,5/5/2023 16:32,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06
4,TX000005,AC00411,13.45,10/16/2023 17:51,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40
5,TX000006,AC00393,92.15,4/3/2023 17:15,Debit,Oklahoma City,D000579,117.67.192.211,M054,ATM,18,Student,172,1,781.68
6,TX000007,AC00199,7.08,2/15/2023 16:36,Credit,Seattle,D000241,140.212.253.222,M019,ATM,37,Doctor,139,1,13316.71
7,TX000008,AC00069,171.42,5/8/2023 17:47,Credit,Indianapolis,D000500,92.214.76.157,M020,Branch,67,Retired,291,1,2796.24
8,TX000009,AC00135,106.23,3/21/2023 16:59,Credit,Detroit,D000690,24.148.92.177,M035,Branch,51,Engineer,86,1,9095.14
9,TX000010,AC00385,815.96,3/31/2023 16:06,Debit,Nashville,D000199,32.169.88.41,M007,ATM,55,Doctor,120,1,1021.88

In [6]:
df.describe(include = 'all')

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
count,50000,50000,50000.000000,50000,50000,50000,50000,50000,50000,50000,50000.000000,50000,50000.000000,50000.00000,50000.000000
unique,50000,495,NaN,6373,2,43,681,592,100,3,NaN,4,NaN,NaN,NaN
top,TX049984,AC00363,NaN,6/12/2021,Debit,Fort Worth,D000548,200.136.146.93,M026,Branch,NaN,Student,NaN,NaN,NaN
freq,1,249,NaN,35,38747,1396,196,261,940,17278,NaN,13059,NaN,NaN,NaN
mean,NaN,NaN,297.872214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.647600,NaN,118.965320,1.12684,5122.738301
std,NaN,NaN,292.818888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.800293,NaN,70.000681,0.60936,3904.266887
min,NaN,NaN,0.240000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.000000,NaN,10.000000,1.00000,101.250000
25%,NaN,NaN,82.897500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,63.000000,1.00000,1508.720000
50%,NaN,NaN,209.355000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.000000,NaN,111.000000,1.00000,4735.410000
75%,NaN,NaN,409.625000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.000000,NaN,161.000000,1.00000,7713.670000
max,NaN,NaN,2060.590000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.000000,NaN,300.000000,5.00000,14977.990000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TransactionID        50000 non-null  object
 1   AccountID            50000 non-null  object
 2   TransactionAmount    50000 non-null  float64
 3   TransactionDate      50000 non-null  object
 4   TransactionType      50000 non-null  object
 5   Location             50000 non-null  object
 6   DeviceID             50000 non-null  object
 7   IP Address           50000 non-null  object
 8   MerchantID           50000 non-null  object
 9   Channel              50000 non-null  object
 10  CustomerAge          50000 non-null  int64
 11  CustomerOccupation   50000 non-null  object
 12  TransactionDuration  50000 non-null  int64
 13  LoginAttempts        50000 non-null  int64
 14  AccountBalance       50000 non-null  float64
dtypes: float64(2), int64(3), object(10)
memory usage: 5.7+ MB

In [8]:
df.isnull().sum()

TransactionID          0
AccountID              0
TransactionAmount      0
TransactionDate        0
TransactionType        0
Location               0
DeviceID               0
IP Address             0
MerchantID             0
Channel                0
CustomerAge            0
CustomerOccupation     0
TransactionDuration    0
LoginAttempts          0
AccountBalance         0
dtype: int64

In [9]:
df['TransactionID'].duplicated().sum()

np.int64(0)

In [11]:
# Convert Camel case to snake_case
df.columns = (
    df.columns
    .str.replace('([a-z0-9])([A-Z])', r'\1_\2', regex=True)
    .str.lower()
)

In [14]:
df.columns

Index(['transaction_id', 'account_id', 'transaction_amount',
       'transaction_date', 'transaction_type', 'location', 'device_id',
       'ip_address', 'merchant_id', 'channel', 'customer_age',
       'customer_occupation', 'transaction_duration', 'login_attempts',
       'account_balance'],
      dtype='object')

In [13]:
df = df.rename(columns = {'ip address':'ip_address'})

In [15]:
# Convert TransactionDate column beacuse above TransactionDate column is string type
df['transaction_date'] = pd.to_datetime(df['transaction_date'], errors = 'coerce')

# Make new metrics/ columns

In [16]:
# For Detect suspicious transaction timing 
df['transaction_hour'] = df['transaction_date'].dt.hour

In [18]:
# For Detect abnormally high activity
df['transactions_per_account'] = df.groupby('account_id')['transaction_id'].transform('count')

In [19]:
# For Detect Multiple devices 
df['device_per_account'] = df.groupby('account_id')['device_id'].transform('nunique')

In [20]:
# For detect many location for one account
df['locations_per_account'] = df.groupby('account_id')['location'].transform('nunique')

In [21]:
# For Detect Normal spending pattern
df['avg_transaction_amount'] = df.groupby('account_id')['transaction_amount'].transform('mean')

In [22]:
# For detect time difference between tranction for detect rapid consecutive transactions.
df = df.sort_values(['account_id', 'transaction_date'])
df['time_diff'] = df.groupby('account_id')['transaction_date'].diff()

In [23]:
df.head(10)

,transaction_id,account_id,transaction_amount,transaction_date,transaction_type,location,device_id,ip_address,merchant_id,channel,...,customer_occupation,transaction_duration,login_attempts,account_balance,transaction_hour,transactions_per_account,device_per_account,locations_per_account,avg_transaction_amount,time_diff
3677,TX003678,AC00001,47.66,2020-08-18 00:00:00,Debit,Denver,D000649,59.12.96.11,M034,Branch,...,Student,37,1,1649.92,0.0,46,2,2,102.633478,NaT
2922,TX002923,AC00001,43.31,2021-01-17 00:00:00,Debit,Denver,D000649,59.12.96.11,M034,Branch,...,Student,37,1,1649.92,0.0,46,2,2,102.633478,152 days 00:00:00
5766,TX005767,AC00001,200.18,2021-06-02 00:00:00,Debit,Atlanta,D000492,45.241.13.208,M003,Online,...,Engineer,178,1,4180.40,0.0,46,2,2,102.633478,136 days 00:00:00
3309,TX003310,AC00001,46.83,2022-10-02 00:00:00,Debit,Denver,D000649,59.12.96.11,M034,Branch,...,Student,37,1,1649.92,0.0,46,2,2,102.633478,487 days 00:00:00
1312,TX001313,AC00001,47.79,2023-09-15 17:00:00,Debit,Denver,D000649,59.12.96.11,M034,Branch,...,Student,37,1,1649.92,17.0,46,2,2,102.633478,348 days 17:00:00
3431,TX003432,AC00001,46.26,2023-10-27 00:00:00,Debit,Denver,D000649,59.12.96.11,M034,Branch,...,Student,37,1,1649.92,0.0,46,2,2,102.633478,41 days 07:00:00
2016,TX002017,AC00001,212.97,2023-11-14 16:56:00,Debit,Atlanta,D000492,45.241.13.208,M003,Online,...,Engineer,178,1,4180.40,16.0,46,2,2,102.633478,18 days 16:56:00
4545,TX004546,AC00001,47.96,2024-01-26 00:00:00,Debit,Denver,D000649,59.12.96.11,M034,Branch,...,Student,37,1,1649.92,0.0,46,2,2,102.633478,72 days 07:04:00
3886,TX003887,AC00001,50.14,2025-04-29 00:00:00,Debit,Denver,D000649,59.12.96.11,M034,Branch,...,Student,37,1,1649.92,0.0,46,2,2,102.633478,459 days 00:00:00
7947,TX007948,AC00001,44.80,NaT,Debit,Denver,D000649,59.12.96.11,M034,Branch,...,Student,37,1,1649.92,NaN,46,2,2,102.633478,NaT

In [24]:
# Connect to SQL / load data to sql
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
username = "postgres"      
password = "Password" 
host = "localhost"         
port = "5432"              
database = "financial_fraud_detection"   

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "bank_detail"  
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

C:\Users\Gautam\AppData\Local\Temp\ipykernel_19108\127986324.py:15: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df.to_sql(table_name, engine, if_exists="replace", index=False)

Data successfully loaded into table 'bank_detail' in database 'financial_fraud_detection'.